Esri/resource-proxy

PHP/proxy.php

fixes for #129. 
@jgravois @bsvensson @phpmaps can you guys review if its good

PHP: check with listed serverurl regarless if mustMatch is true or false

---

PHP/proxy.php

This is hopefully a clean pull request.
Made sure that the proxy captures the incoming request headers from the client and uses them when making the cURL request.
Next the PHP proxy reads the cURL response and collects all the headers. These headers are then sent to the client along with the response.
This fixes reports of truncated responses. This was b/ the Content-Length property was incorrect. The proxy now calculates Content-Length and sets the proper Content-Length property.

Solves truncated proxy results, fixes 190

---

DotNet/proxy.ashx

This fixes #188 based on the code that @jwoyame suggested in that issue.

Only ask for system proxy once, #188

---

DotNet/proxy.ashx

fixed question mark in password

---

DotNet/proxy.ashx

Changed TraceSwitchName to be different from the one in Web.config.
Removed duplicate timestamp in ping log.

Log level change trace switch name #127

---

Java/proxy.jsp

mimic #211 from DotNet to fix #210

JSP:fixed question mark in password

---

DotNet/proxy.ashx
PHP/proxy.php

Allow host redirecting with proxy

Update proxy.ashx: allow host redirecting in proxy.config

---

.gitignore
Java/proxy.jsp

Fixed the "Already Connect" Issue #182. Refactor the PR #235 to reduce function overload of doHTTPRequest()

Fix the "Already Connect"

---

Java/proxy.jsp

Fix the HTTP-HTTPS bug in jsp proxy

---

Java/proxy.jsp

This PR fixes the #177 and is a enhancement of the PR #238. It also correct the wrong use of URLEncoder (It shouldn't be used against all query string but only key/values in the query string see this [SOF post](http://stackoverflow.com/questions/10786042/java-url-encoding-of-query-string-parameters))

Fix the AGS 10.3.x token authentication issue. Rectify the use of URLEncoder

---

Java/proxy.jsp

* [Improper Resource Shutdown or Release](http://cwe.mitre.org/data/definitions/404.html)
* [Information Exposure Through Sent Data](http://cwe.mitre.org/data/definitions/201.html)
* [Use of Wrong Operator in String Comparison](http://cwe.mitre.org/data/definitions/597.html)

Fix a couples of issues from static scan

---

Java/proxy.jsp

Should fix the issue mentioned in #148. This is an enhanced version of the #148 
cc: @bsvensson @vtforester

Client side check for token expiration

---

Java/proxy.jsp

Clean up redundant statements/variables, simplify the logic,  reconcile the code style, add comments
Check against all the existing test cases

JSP: Refactor / make code consistent 

---

Java/proxy.jsp

This should fix the #191 on JSP. Tested against all test cases. cc: @bsvensson

JSP: Add support for federated server

---

DotNet/proxy.ashx
Java/proxy.jsp

Contain an enhancement to #245

Fix the token expiration for DotNet and JSP

---

Java/proxy.jsp
PHP/proxy.php

Similar to #174, but on JSP and PHP. Tested against all existing test cases.

Remove Accept Ranges in HTTP Header

---

DotNet/proxy.ashx

Tested against all the test cases.

Delete the redundant variable "passThrough" and simply the relevant logic

---

Java/proxy.jsp

This should fix #240. Tested against all the test cases. cc: @bsvensson

Add JSP allow host redirect

---

DotNet/proxy.ashx

Fix the issue of host redirect when requesting token

---

PHP/proxy.php

Refactor: sessonKey -> sessionKey

---

DotNet/proxy.ashx

Tested. Fixed this issue #191 on DotNet.

Add federated service authentication for DotNet

---

PHP/proxy.php

Fix bug: php proxy requesting 10.3.1 html page. @bsvensson (also fixed a code style issue)

Fix bug: php proxy requesting 10.3.1 html page.

---

PHP/proxy.php

Add PHP support for federated services

---

CHANGELOG.md
DotNet/README.md
DotNet/proxy.ashx
Java/proxy.jsp
PHP/proxy.php

Semantic versioning and Unreleased section in change log

---

PHP/proxy.php

Handle 10.3 server token expiration. Similar to #256

Php token expire

---

PHP/proxy.php

1. !==null -> isset()
2. == -> ===

Refactor the php code:

---

CHANGELOG.md

@bsvensson lets use this (in favor of #274) as i missed yours and made a few other minor copyedits.

added comparison links to changelog

---

PHP/proxy.php

Transfer correct HTTP status code to client. Tested against all test cases

Php 403header

---

Java/proxy.jsp

JSP handling regarding CRLF in log file and in HTTP header.

JSP: CRLF handling

---

README.md

resolves #199.  right on time :smile:

add faq link to readme

---

DotNet/README.md
DotNet/proxy.xsd

@afili or @jgravois - please review this doc update based on PR #118 by Artemis.

Doc the "domain" property #269

---

PHP/proxy.php

Implement the full PHP handling of allowedReferer. Tested against all test cases.

Implement the full PHP handling of allowedReferer (for #282)

---

DotNet/proxy.ashx

similar to #281. Tested against all test cases

DotNet handle of the allowedReferer (for #282)

---

README.md

PR for https://github.com/Esri/resource-proxy/issues/298
Update to master README with troubleshooting and links to specific
products. Could be grown or contracted over time, but offers a one stop shop resource for all things proxy.

update to master README with troubleshooting and links to specific products

---

DotNet/README.md
Java/README.md
PHP/README.md
README.md

unduplicate proxy.config doc and samples

---

README.md

@patrickarlt @esoekianto - can you review this new section I'm proposing?

Add "Alternatives" section

---

DotNet/proxy.ashx

At least until John's idea for JSON handling is implemented

Proposal for #386 and #387

---

Java/proxy.jsp

Fix for JSP: ERR_INVALID_CHUNKED_ENCODING error when data is chunked.
https://github.com/Esri/resource-proxy/issues/420

java: remove chunked header for client response

---

CHANGELOG.md
DotNet/proxy.ashx
Java/proxy.jsp
PHP/proxy.php

@jgravois @esoekianto - please review and merge. Should be pretty straight-forward :)
See longer discussion in #316.

Stop using beta in version string, #316

---

PHP/proxy.php

PHP Version 7.1.1. Default value was added to avoid getting 500 Internal Server Error message.

Added default value

---

.gitignore
DotNet/proxy.xsd

Add logLevel in XSD

---

DotNet/proxy.ashx
README.md

Put repo back into most recent state after bot accidentally deleted master branch.

Resync repo
