Esri/resource-proxy

- Java/proxy.jsp
Without this pull request the Context-Type is text/html (tomcat's default).
With this pull request the Context-Type is application/json.
> JSP: set Content-Type for errors to json , #205

- DotNet/proxy.ashx
Use app.config proxy settings from the app.config file. If there is no
config file, the current user's Internet Explorer (IE) proxy settings
are used
https://msdn.microsoft.com/en-us/library/system.net.webrequest.defaultwebproxy.aspx
> Use app.config proxy setting

- DotNet/proxy.ashx
Fixed #166 in DotNet
"sub.domain.com" - accept both http and https
"sub.domain.com/folder" - accept both http and https
"http://sub.domain.com" - accept only http
"https://sub.domain.com/folder" - accept only https
"//sub.domain.com" - accept both http and https
"*.domian.com" - accept both http, https, all the subdomains and folders.
> DotNet: Support more format for allowed referer #166

- Java/proxy.jsp
JSP implementation of #215.
But on the top of all rules stated in #215, we also allow parent directory matching, i.e. if `allowReferer = sub.domain.com/folder` and HTTP Referer = sub.domain.com/folder/app.html, the request will be passed alone. We also block the request with HTTP Referer = sub.domain.com/folder_plus_sth
> JSP: Improve the versatile allowReferer handling (for #282)

- DotNet/proxy.ashx
as per @bsvensson's comment [here](https://github.com/Esri/resource-proxy/issues/69#issuecomment-133227514).
this code change is entirely untested, (as i don't have a .NET development machine set up anymore) so please confirm all is well prior to merging.
speaking of which, have you given any more thought to adding automated tests to the repo itself?  i still think its a worthwhile endeavor.
> utilize 429 error and custom description when ratelimit is exceeded

- DotNet/proxy.ashx
Add mustMatch check logic in GetConfigServerUrl(string uri).
Return a new ServerUri object when mustMatch is false to avoid the
incorrect error message.
Add constructors in ServerUrl class.
> Fixed bug #294

- Java/proxy.jsp
I work on an application that is stuck on JDK 1.6.
When trying to run the Java\proxy.jsp in this project there were several cases of shorthand generic type definition (diamond type) being defined - a JDK 1.7 specific feature.
The pull request replaces this with the longhand version so that the JSP runs against JDK 1.6.
> Change to remove JDK 1.7 shorthand for generic types

- DotNet/proxy.xsd
The ashx file uses "oauth2Endpoint"
> Corrected oAuth endpoint variable name

- DotNet/proxy.ashx
Added quotes to the error response, so it becomes well formed JSON. This
allows the error to be captured in the client code by using JSON.Parse.
> Change error response to be well-formed JSON

- DotNet/proxy.ashx
Do not copy access-control-* headers from remote server response, they should be set by http-proxy webserver (and they can't be duplicated in response either).
> Do not copy access-control-* headers

- DotNet/proxy.ashx
Eliminates the 'System.Threading.ThreadAbortException' that is thrown every time proxy.ashx runs in Visual Studio.
> Changed method for completing the response to the web client. 

- DotNet/README.md
- DotNet/proxy.ashx
- DotNet/proxy.xsd
- README.md
Added additional boolean 'useAppPoolIdentity' property to the ServerUrl object that will trump the 'domain', 'username' and 'password' properties.  This 'useAppPoolIdentity' will inherit the configured IIS Application Pool identity by using the 'CredentialCache.DefaultNetworkCredentials' in 'System.Net' .
> Pfoppe patch 1 support app pool identity

- DotNet/proxy.ashx
* Removed conflicts from the changes from @jwoyame #186. (#175)
* Also making sure the list of headers that are in #362 are not passed along.
> Copy original HTTP request headers

- PHP/proxy.php
Tested locally with php 5.5 and php 7.0.0
> Support attachments for php5.6+, #364

- PHP/proxy.php
The XmlParser class is still using the old php4 method of constructors sharing the same name as the class. Changed construct style to php5^.
> Fix same name constructor error

- README.md
i'd consider incrementally bumping the changelog as each pull request lands using the `[Unreleased]` section ideal.
That said, there's nothing wrong with isolating the commit history since the last release and doing it all at once immediately before publishing either.
https://github.com/Esri/resource-proxy/compare/v1.1.2...HEAD
> include steps for tagging releases in the README

- DotNet/proxy.ashx
When used against LocatorHub (our version was 10.2.2), the LocatorHub responses contain escaped forward slashes (`\/`), which in turn causes the requests to end up with the following exception: 
UriFormatException: Invalid URI: The hostname could not be parsed.
Therefore, we need to unescape the JSON values when they are extracted from the responses to ensure the URIs and tokens are clean.
This effectively addresses #474
> Unescape JSON values to avoid malformed URIs

- .gitignore
- DotNet/proxy.ashx
- DotNet/proxy.config
- DotNet/proxy.xsd
Add Intellisense VS in proxy.config
> Add Intellisense in proxy.config

- DotNet/Web.config
A solution to #399 
This solution requires .net 4.5
> Require .net 4.5 in order to support SecurityProtocolType.Tls12

- PHP/proxy.php
Update `proxyPost()` constructor properties to accept null values, similar to `proxyGet()`. Closes  #473.
> Fix php 7 POST request bug

- PHP/proxy.php
Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!
> Change PHP keywords to comply with PSR2

- DotNet/proxy.ashx
This PR fixes #554
The way the code currently is, people pulling in this file will have a new warning in their project. Seems like a library should try not to generate warnings in other peoples' projects.
Should be extremely low-risk to merge this in.  Just helpful for anyone else who uses the resource-proxy in the future.
> Removed an unused variable name
